### ISSUE TITLE
Error page when submitting a URL to dataset, even though the submission is successful.

### ISSUE THREAD

**Issue by eliasvagan** [OpenDataNTNU/OpenData#214]

**Comment by MittBrukernavn** [comment]
Does this happen from a clean run? We labeled this as a bug very quickly without checking the actual error. Could be jitter from another branch

**Comment by AndreasJJ** [comment]
<img width="827" alt="Skjermbilde 2020-03-25 kl  12 56 33" src="https://user-images.githubusercontent.com/15128509/77533958-213dbd00-6e98-11ea-86b6-c2da76e59d9a.png">

Det skjer når man legger ut et dataset med en type for første gang. F.eks. første gang man legger til en url med CSV for første gang

**Comment by MittBrukernavn** [comment]
Looks like it only happens if a date is supplied. Looking into where the error lies.

**Comment by MittBrukernavn** [comment]
Nvm, I think I misinterpreted Andreas' message. It does indeed seem like his analysis was correct.

**Comment by MittBrukernavn** [comment]
As far as I can tell, the PUT request itself returns `null` as the data format when you put in those conditions - the frontend breaks because it expects a dataFormat object. The exact conditions, as far as I can tell, are:

- some new data source of format A is added to dataset B
- dataset B does not have any previous data sources of format A

**Comment by MittBrukernavn** [comment]
This turned out to be a dissonance between what the APi supplied and what the frontend expected. It works as expected now that the API returns the object that it creates.
